name: Docker Image Publish to DockerHub

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Listing files
      run: ls -ll
    - name: Build the Docker image
      run: |
        docker build . -t waqardocker123/my-pipeline-test-image
        docker image ls

    - name: Pushing Image to DockerHub
      run: |
        echo "dckr_pat_YHpvi2QU-gcHprSJzzQn2AVQwQM" | docker login -u waqardocker123 --password-stdin
        docker push waqardocker123/my-pipeline-test-image
        
